[tool.poetry]
name = "pfhedge"
version = "0.20.0"
description = "Deep Hedging in PyTorch"
authors = ["Shota Imaki <shota.imaki.0801@gmail.com>"]
license = "MIT"
repository = "https://github.com/pfnet-research/pfhedge"

[tool.poetry.dependencies]
python = "^3.8"
torch = "^1.9.0"
tqdm = "^4.62.3"
scipy = {version = "^1.10.1", python=">=3.8,<3.12"}
jax= "^0.4.7"
jaxlib = "^0.4.7"
pennylane="^0.29.0"
pyyaml = "^6.0"
seaborn = "^0.12.2"
flask = "^2.2.3"
qiskit = "^0.43.2"
pylatexenc = "^2.10"
dill = "^0.3.6"

[tool.poetry.dev-dependencies]
pytest = "^6.2.5"
black = "^22.3.0"
isort = "^5.9.3"
mypy = "^0.910"
pytest-cov = "^3.0.0"
Sphinx = "^4.2.0"
sphinx-autobuild = "^2021.3.14"
sphinx-copybutton = "^0.4.0"
furo = "^2021.9.22"
codecov = "^2.1.12"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
skip-magic-trailing-comma = true

[tool.isort]
profile = 'black'
force_single_line = true

[tool.pytest.ini_options]
addopts = "-m \"not gpu\""
markers = "gpu: Tests that require GPU"
